### ISSUE TITLE
iOS artefacts not being published to Maven

### ISSUE THREAD

**Issue by jmacindoe** [soil-kt/soil#110]
**Which version of Soil are you using**
1.0.0-alpha06

**Issue**
I'm unable to build my project for iOS when including soil. It looks like the iOS artefacts are not being published to maven. Compare for example:
wasm-js: https://mvnrepository.com/artifact/com.soil-kt.soil/query-compose-wasm-js
iosarm64: https://mvnrepository.com/artifact/com.soil-kt.soil/query-compose-iosarm64

iOS only has artefacts for 1.0.0-alpha01

Awesome library by the way!

**Comment by ogaclejapan** [comment]
Thank you for the report!

It looks like the iOS artifacts weren't uploaded correctly 😢
I'll investigate why the CI upload process isn’t working as expected.

**Comment by ogaclejapan** [comment]
Hi, @jmacindoe

I’ll be releasing the next version this weekend, which will fix this issue. 
I’m really glad you brought it to my attention—thank you so much! 😄

**Comment by jmacindoe** [comment]
Awesome. Looking forward to the next version. Really great work with the library 👍

**Comment by ogaclejapan** [comment]
`1.0.0.alpha07` has been released and iOS artifacts are now available 🎉 

- https://central.sonatype.com/artifact/com.soil-kt.soil/query-compose-iosarm64

**Comment by ogaclejapan** [comment]
Retrieving comment information

**Comment by ogaclejapan** [comment]
test

**Comment by ogaclejapan** [comment]
コメント内容を確認したいです
